### ISSUE TITLE
adding section numbering to markdown preview enhanced css

### ISSUE THREAD

**Issue by awillats** [awillats/markdown-manuscript-template#8]
https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css
https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/1446
https://support.typora.io/Auto-Numbering/

**Comment by awillats** [comment]
```css
/* Please visit the URL below for more information: */
/*   https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css */

.markdown-preview.markdown-preview {
  // modify your style here
    /* Heading numbering, inspired by Typora 
     https://support.typora.io/Auto-Numbering/
    */  
    // .do-number-sections()
      
  }
  
  .do-number-sections{
      
    counter-reset: h1;

    h1 {
      counter-reset: h2
    }

    h2 {
        counter-reset: h3
    }

    h3 {
        counter-reset: h4
    }

    h4 {
        counter-reset: h5
    }

    h5 {
        counter-reset: h6
    }

    h1:before {
        counter-increment: h1;
        content: counter(h1) ". "
    }

    h2:before {
        counter-increment: h2;
        content: counter(h1) "." counter(h2) ". "
    }
    h3:before{
        counter-increment: h3;
        content: counter(h1) "." counter(h2) "." counter(h3) ". "
    }

    h4:before{
        counter-increment: h4;
        content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) ". "
    }

    h5:before{
        counter-increment: h5;
        content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) ". "
    }
    h6:before{
        counter-increment: h6;
        content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) ". "
    }
  }
```
